
EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-12345678 # replace with your AMI ID
      InstanceType: t2.micro
      KeyName: !Ref Key-Pair
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet:
            - !Ref EC2SecurityGroup
          SubnetId: !Ref PublicSubnet

  EC2Instance2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-05c13eab67c5d8861"
      InstanceType: "t2.micro"
      KeyName: "EC2Instance2"
      SecurityGroupIds:
        - 'sg-02459b5028487c77a'  # Specify the security group ID
      SubnetId: 'subnet-0b8a35c402bd737dc'  # Private subnet ID
  


  

  

  

  

  

  
